/**
 * Feature-comparison doc sync — PR driver.
 *
 * Runs on every push to `master` (i.e. right after a PR merges). It regenerates
 * `docs/lite/02-feature-comparison.md` from the source of truth
 * (`lab/lite/docs/feature-comparison.html`) via `scripts/gen-feature-comparison.ts`,
 * and — ONLY if that produced a change — opens a companion pull request with the
 * regenerated doc.
 *
 * Why a companion PR (rather than committing to master or to the merged PR branch):
 *   - Fork-safe: the contributor's PR may have come from a fork we can't push to.
 *   - One-click accept: a maintainer just merges the auto-PR.
 *   - No surprise commits on master; the doc update is reviewable.
 *
 * Idempotent: if the doc is already in sync (the common case — most PRs don't touch
 * the feature table), this is a noop with no branch and no PR.
 *
 * Required env:
 *   - GITHUB_TOKEN        token with `contents:write` + `pull_requests:write`
 *   - GITHUB_REPOSITORY   e.g. "BabylonJS/Babylon-Lite"
 * Optional env:
 *   - BASE_BRANCH         default "master"
 *   - GIT_USER_NAME       default "Babylon.js CI"
 *   - GIT_USER_EMAIL      default "bjsplat@gmail.com"
 *   - DRY_RUN             when "true", regenerate + report but do not push / open a PR
 */

import { execFileSync } from "child_process";
import { syncFeatureDoc } from "./gen-feature-comparison.js";

const REPO = requireEnv("GITHUB_REPOSITORY");
const TOKEN = requireEnv("GITHUB_TOKEN");
const BASE_BRANCH = process.env.BASE_BRANCH ?? "master";
const GIT_USER_NAME = process.env.GIT_USER_NAME ?? "Babylon.js CI";
const GIT_USER_EMAIL = process.env.GIT_USER_EMAIL ?? "bjsplat@gmail.com";
const DRY_RUN = process.env.DRY_RUN === "true";

const DOC_PATH = "docs/lite/02-feature-comparison.md";
const PR_LABELS = ["documentation", "automation"];

async function main(): Promise<void> {
    // 1. Regenerate the doc from the lab HTML (source of truth).
    const result = syncFeatureDoc();

    // 2. Did regeneration change the doc? If not, it already matches the HTML — noop.
    //    (After a clean merge to master the tree is clean, so the generator's own
    //    signal is authoritative for "is there anything to sync".)
    if (!result.changed) {
        console.log(`${DOC_PATH} is already in sync with the lab HTML. Nothing to do (noop).`);
        return;
    }
    console.log(`${DOC_PATH} drifted from the lab HTML — preparing a sync PR.`);

    // 3. Branch, commit, push, open PR.
    const date = new Date().toISOString().slice(0, 10);
    const branch = `feature-doc-sync/${date}`;

    configureGit();
    runGit(["checkout", "-b", branch]);
    runGit(["add", DOC_PATH]);
    runGit(["commit", "-m", commitMessage(date)]);

    if (DRY_RUN) {
        console.log(`[dry-run] Would push ${branch} to ${REPO} and open a PR. Diff:`);
        console.log(runGit(["show", "--stat", "HEAD"]));
        return;
    }

    const pushUrl = `https://x-access-token:${TOKEN}@github.com/${REPO}.git`;
    runGit(["push", "--force-with-lease", pushUrl, `HEAD:refs/heads/${branch}`]);
    const { url, number } = await openPullRequest(branch);
    await applyLabels(number);
    console.log(`Opened feature-doc sync PR: ${url}`);
}

function commitMessage(date: string): string {
    // Conventional-commit "docs" scope so the npm release pipeline never treats a doc
    // sync as a feature/breaking change in @babylonjs/lite.
    return [
        `docs(lite): sync feature comparison from lab (${date})`,
        "",
        "Regenerated docs/lite/02-feature-comparison.md from",
        "lab/lite/docs/feature-comparison.html via scripts/gen-feature-comparison.ts.",
        "",
        "Co-authored-by: Copilot <223556219+Copilot@users.noreply.github.com>",
    ].join("\n");
}

async function openPullRequest(branch: string): Promise<{ url: string; number: number }> {
    const diffstat = runGit(["show", "--stat", "--oneline", "HEAD"]);
    const title = "docs(lite): sync feature comparison from lab";
    const body = [
        "Automated sync of the feature-comparison doc.",
        "",
        `The source of truth — \`lab/lite/docs/feature-comparison.html\` — changed, so`,
        `\`${DOC_PATH}\` was regenerated by [\`scripts/gen-feature-comparison.ts\`](scripts/gen-feature-comparison.ts)`,
        "to match. The hand-written intro, legend, and trailing prose (outside the AUTOGEN markers) are untouched.",
        "",
        "Merge to publish the updated comparison table. To preview locally: `pnpm gen:feature-doc`.",
        "",
        "### Regenerated",
        "```",
        diffstat.trim(),
        "```",
    ].join("\n");

    const response = await fetch(`https://api.github.com/repos/${REPO}/pulls`, {
        method: "POST",
        headers: {
            Authorization: `Bearer ${TOKEN}`,
            Accept: "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        body: JSON.stringify({ title, head: branch, base: BASE_BRANCH, body }),
    });

    if (!response.ok) {
        throw new Error(`Failed to open PR (${response.status}): ${await response.text()}`);
    }
    const json = (await response.json()) as { html_url?: string; number?: number };
    return { url: json.html_url ?? "(unknown URL)", number: json.number ?? 0 };
}

/** Apply the automation labels to the freshly-opened PR (best-effort). */
async function applyLabels(prNumber: number): Promise<void> {
    if (!prNumber) {
        return;
    }
    const response = await fetch(`https://api.github.com/repos/${REPO}/issues/${prNumber}/labels`, {
        method: "POST",
        headers: {
            Authorization: `Bearer ${TOKEN}`,
            Accept: "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        body: JSON.stringify({ labels: PR_LABELS }),
    });
    if (!response.ok) {
        // Non-fatal: labels may not exist in the repo. Log and continue.
        console.warn(`Could not apply labels (${response.status}): ${await response.text()}`);
    }
}

function configureGit(): void {
    runGit(["config", "user.name", GIT_USER_NAME]);
    runGit(["config", "user.email", GIT_USER_EMAIL]);
}

function runGit(args: string[]): string {
    return execFileSync("git", args, { cwd: process.cwd(), encoding: "utf-8", stdio: ["ignore", "pipe", "pipe"] }).trim();
}

function requireEnv(name: string): string {
    const value = process.env[name];
    if (!value) {
        throw new Error(`Missing required environment variable: ${name}`);
    }
    return value;
}

/** Strip the auth token from any string before it can be logged. */
function redactToken(text: string): string {
    return TOKEN ? text.split(TOKEN).join("***") : text;
}

main().catch((error: unknown) => {
    console.error(redactToken(error instanceof Error ? error.message : String(error)));
    process.exit(1);
});
